(() => {
'use strict';
const D=window.EXHIBIT;
const chapters=['journey','features','technology','future'];
const labels=['JOURNEY','FEATURES','TECHNOLOGY','FUTURE'];
let active='journey',group=0,tech=0,tour=null,remaining=25,lastFocus=null;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('.skip').addEventListener('click',e=>{e.preventDefault();$('#main').focus();});
const num=n=>String(n+1).padStart(2,'0');
const icons={scan:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M7 12h10M12 7v10"/>',layers:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',text:'<path d="M4 4h16M8 4v16m8-16v16M4 11h16M4 20h16"/>',archive:'<path d="M3 4h18v5H3zM5 9v12h14V9M9 13h6"/>',people:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5v2"/>',chip:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 1v5m6-5v5M9 18v5m6-5v5M1 9h5m-5 6h5m12-6h5m-5 6h5"/>',move:'<path d="M12 3v18M3 12h18M8 7l4-4 4 4M8 17l4 4 4-4M7 8l-4 4 4 4m10-8 4 4-4 4"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[k]||icons.layers}</svg>`;
function showDialog(kicker,title,body){stopTour();lastFocus=document.activeElement;$('#dialog-content').innerHTML=`<p class="eyebrow">${esc(kicker)}</p><h2 id="dialog-title">${esc(title)}</h2>${body}`;$('#detail-dialog').showModal();$('#detail-dialog').scrollTop=0;}
function closeDialog(){$('#detail-dialog').close();}
$('#detail-dialog .dialog-close').addEventListener('click',closeDialog);
$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
$('#detail-dialog').addEventListener('close',()=>{if(lastFocus&&document.contains(lastFocus))lastFocus.focus({preventScroll:true});});
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function selectEdp(i){const d=D.edp[i];$$('.edp-step').forEach((b,j)=>{b.classList.toggle('selected',j===i);b.setAttribute('aria-pressed',String(j===i));});$('#edp-detail').innerHTML=`<span class="detail-number" aria-hidden="true">${num(i)}</span><p class="eyebrow">${esc(d.label)}</p><h2>${esc(d.title)}</h2><p>${esc(d.body)}</p><div class="takeaway"><span>DESIGN REQUIREMENT</span><p>${esc(d.takeaway)}</p></div><button class="text-button" data-edp-more="${i}">Explore this stage <span aria-hidden="true">+</span></button>`;}
$('#edp-steps').setAttribute('role','group');$('#edp-steps').setAttribute('aria-label','Engineering Design Process stages');
$$('.edp-step').forEach((b,i)=>b.addEventListener('click',()=>{stopTour();selectEdp(i);}));
$('#edp-detail').addEventListener('click',e=>{const b=e.target.closest('[data-edp-more]');if(b){const d=D.edp[Number(b.dataset.edpMore)];showDialog('OUR ENGINEERING DESIGN PROCESS',d.label,`<p>${esc(d.body)}</p><p>${esc(d.evidence)}</p><div class="dialog-note"><h3>What this means for Punaruttham</h3><p>${esc(d.takeaway)}</p></div>`);}});
$('.edp-card').insertAdjacentHTML('beforeend',`<div class="print-only">${D.edp.map((d,i)=>`<p><strong>${num(i)} ${esc(d.label)}.</strong> ${esc(d.takeaway)}</p>`).join('')}</div>`);
$('#teamwork-button').addEventListener('click',()=>showDialog('OUR TEAM','Different strengths. Shared ownership.',`<div class="team-dialog-grid"><div><h3>Amor · hardware & mechanics</h3><p>Rover body, modular construction, mechanical integration, scanning movement and the lift.</p></div><div><h3>Sankalp · software & intelligence</h3><p>Target detection, mode selection, interpretation, confidence displays, reports and digital records.</p></div></div><div class="dialog-note"><h3>At the interfaces, we work together</h3><p>Thermal/depth sensing, camera viewpoints, damage mapping and automated lift alignment connect our two areas. The complete scan-to-archive workflow depends on both.</p></div><p>Our presentation connects explanation and operation: one teammate explains the problem and engineering decisions while the other demonstrates the system. The EDP gives us a shared language for choosing, testing and improving.</p>`));
const featureTotal=D.featureGroups.reduce((n,g)=>n+g.items.length,0);
$('#features-panel').innerHTML=`<div class="section-heading"><div><p class="eyebrow">02 / FEATURES & CAPABILITIES</p><h1 id="features-title">What Punaruttham does.</h1><p class="section-intro">Select any icon to explore the capability.</p></div><div class="section-stamp"><strong>${featureTotal}</strong><span>CONNECTED CAPABILITIES<small>One scan-to-archive workflow</small></span></div></div><div class="icon-directory feature-directory">${D.featureGroups.map((g,i)=>`<section class="directory-column"><div class="directory-heading"><span>${num(i)}</span><div><h2>${esc(g.title)}</h2><p>${esc(g.subtitle)}</p></div></div><div class="directory-items">${g.items.map((f,j)=>`<button class="directory-item" data-feature-group="${i}" data-feature="${j}"><span class="directory-icon">${icon(g.icon)}</span><span>${esc(f[0])}</span><span class="directory-plus" aria-hidden="true">+</span></button>`).join('')}</div></section>`).join('')}</div><div class="principle-strip"><span>OUR PRESERVATION PRINCIPLE</span><p>Original evidence stays visible. Proposed reconstructions stay distinguishable. Experts remain part of the process.</p></div>`;
$$('[data-feature]').forEach(b=>b.addEventListener('click',()=>{const g=D.featureGroups[Number(b.dataset.featureGroup)],f=g.items[Number(b.dataset.feature)];showDialog('FEATURES / '+g.title,f[0],`<p class="dialog-lead">${esc(f[1])}</p><p>${esc(f[2])}</p><div class="dialog-note"><h3>Why it matters</h3><p>${esc(f[3])}</p></div>`);}));
$('#technology-panel').innerHTML=`<div class="section-heading"><div><p class="eyebrow">03 / TECHNOLOGY & ARCHITECTURE</p><h1 id="technology-title">Inside Punaruttham.</h1><p class="section-intro">Select any icon to explore its role in the system.</p></div><div class="tech-badge">USB camera <span>/</span> Laptop <span>/</span> Hybrid AI</div></div><div class="icon-directory tech-directory">${D.technology.map((t,i)=>`<section class="directory-column"><div class="directory-heading"><span>${num(i)}</span><div><h2>${esc(t.name)}</h2><p>${esc(t.kicker)}</p></div></div><div class="directory-items">${t.components.map((c,j)=>`<button class="directory-item" data-tech-group="${i}" data-component="${j}"><span class="directory-icon">${icon(t.icon)}</span><span>${esc(c[0])}</span><span class="directory-plus" aria-hidden="true">+</span></button>`).join('')}</div></section>`).join('')}</div><div class="principle-strip"><span>THE CONTROL LOOP</span><p>Vision locates the target. The controller positions the scanner. Capture waits for readiness. Evidence flows into analysis and the archive.</p></div>`;
$$('[data-component]').forEach(b=>b.addEventListener('click',()=>{const t=D.technology[Number(b.dataset.techGroup)],c=t.components[Number(b.dataset.component)];showDialog('TECHNOLOGY / '+t.name,c[0],`<p class="dialog-lead">${esc(c[1])}</p><p>${esc(c[2])}</p><div class="dialog-note"><h3>Its place in the system</h3><p>${esc(t.description)}</p></div>`);}));
$('#future-panel').innerHTML=`<div class="section-heading"><div><p class="eyebrow">04 / FUTURE & WIDER IMPACT</p><h1 id="future-title">A future worth preserving.</h1><p class="section-intro">Extend access, deepen the evidence and take preservation into more places.</p></div><div class="segmented" role="group" aria-label="Future view"><button data-future-view="roadmap" class="selected" aria-pressed="true">Future roadmap</button><button data-future-view="business" aria-pressed="false">Access model</button></div></div><div id="roadmap-view"><div class="future-columns"><div class="future-column"><div class="horizon-heading"><span>01</span><div><p class="eyebrow">EXPAND ACCESS</p><h2>Put preservation within reach.</h2></div></div>${futureCard(D.future[0])}${futureCard(D.future[1])}</div><div class="future-column"><div class="horizon-heading"><span>02</span><div><p class="eyebrow">DEEPEN IMPACT</p><h2>Make the evidence stronger.</h2></div></div>${futureCard(D.future[2])}${futureCard(D.future[3])}${futureCard(D.future[4])}</div><div class="future-column"><div class="horizon-heading"><span>03</span><div><p class="eyebrow">EXPLORE FURTHER</p><h2>Open new possibilities.</h2></div></div>${futureCard(D.future[5])}${futureCard(D.future[6])}<div class="future-quote"><span>THE LONG-TERM VISION</span><p>A record that remains useful even when the original becomes harder to read.</p></div></div></div></div><div id="business-view" hidden><div class="business-intro"><h2>Access without owning every capability.</h2><p>A modular model for institutions with different needs, budgets and periods of use.</p></div><div class="business-canvas">${D.business.map(b=>`<button class="canvas-block canvas-${b[0]}" data-business="${b[0]}"><span class="eyebrow">${esc(b[1])}</span><h3>${esc(b[2])}</h3><span class="card-plus" aria-hidden="true">+</span></button>`).join('')}</div><div class="rental-flow"><strong>THE MODULE LIBRARY</strong><span>Select a capability</span><span>Record its condition</span><span>Use & return</span><span>Inspect & repair</span><span>Recirculate</span></div></div><div class="principle-strip"><span>FROM THIS BOOTH TO THE FIELD</span><p>Expert-supervised pilots, accessible tools and reusable modules guide our next steps.</p></div>`;
function futureCard(f){return `<button class="future-card" data-future="${f.id}"><span class="eyebrow">${esc(f.category)}</span><h3>${esc(f.title)}</h3><p>${esc(f.body)}</p><span class="card-plus" aria-hidden="true">+</span></button>`;}
$$('[data-future]').forEach(b=>b.addEventListener('click',()=>{const f=D.future.find(f=>f.id===b.dataset.future);showDialog('FUTURE / '+f.category,f.title,`<p>${esc(f.body)}</p><ul>${f.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><div class="dialog-note"><h3>What this opens up</h3><p>${esc(f.outcome)}</p></div>`);}));
$$('[data-business]').forEach(b=>b.addEventListener('click',()=>{const item=D.business.find(x=>x[0]===b.dataset.business);showDialog('FUTURE / ACCESS MODEL',item[1],`<p class="dialog-lead">${esc(item[2])}</p><p>${esc(item[3])}</p>`);}));
function futureView(v){$('#roadmap-view').hidden=v!=='roadmap';$('#business-view').hidden=v!=='business';$$('[data-future-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.futureView===v);b.setAttribute('aria-pressed',String(b.dataset.futureView===v));});}
$$('[data-future-view]').forEach(b=>b.addEventListener('click',()=>{stopTour();futureView(b.dataset.futureView);}));
function showChapter(id,{scroll=true}={}){if(!chapters.includes(id)&&id!=='home')id='home';active=id;$('.chapter-nav').hidden=id==='home';$$('[data-panel]').forEach(s=>s.hidden=s.dataset.panel!==id);$$('.chapter').forEach(a=>{const selected=a.hash==='#'+id;a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#chapter-position').textContent=id==='home'?'FOUR INTERACTIVE POSTERS':num(chapters.indexOf(id))+' — '+labels[chapters.indexOf(id)];document.title=id==='home'?'Punaruttham · International WRO':'Punaruttham · '+labels[chapters.indexOf(id)]+' · International WRO';if(scroll)window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',()=>{showChapter(location.hash.slice(1));});
$$('.chapter,.brand,.quadrant,.home-link').forEach(a=>a.addEventListener('click',()=>{stopTour();if(location.hash===a.hash)showChapter(a.hash.slice(1));}));
function navigate(id){if(location.hash==='#'+id)showChapter(id);else location.hash=id;}
function stopTour(){if(tour){clearInterval(tour);tour=null;}$('#tour-button').setAttribute('aria-pressed','false');$('#tour-status').hidden=true;}
function startTour(){if($('#detail-dialog').open)closeDialog();remaining=25;$('#tour-button').setAttribute('aria-pressed','true');$('#tour-status').hidden=false;$('#tour-countdown').textContent=remaining+'s';tour=setInterval(()=>{if(document.hidden)return;remaining--;if(remaining<=0){remaining=25;const next=chapters[(chapters.indexOf(active)+1)%4];navigate(next);}$('#tour-countdown').textContent=remaining+'s';},1000);}
$('#tour-button').addEventListener('click',()=>tour?stopTour():startTour());$('#stop-tour').addEventListener('click',stopTour);
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Use your browser’s fullscreen or presentation command.');}catch{toast('Use your browser’s fullscreen or presentation command.');}}
$('#fullscreen-button').addEventListener('click',fullscreen);document.addEventListener('fullscreenchange',()=>$('#fullscreen-button').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen'));
$('#help-button').addEventListener('click',()=>showDialog('EXHIBIT CONTROLS','Make the booth your own.',`<p>The landscape overview has four quadrants. Select one to open its poster, then touch a stage or icon to explore it. Each chapter also has its own link for a dedicated display.</p><div class="key-row"><kbd>1 2 3 4</kbd><span>Open a chapter</span></div><div class="key-row"><kbd>← / →</kbd><span>Previous / next chapter</span></div><div class="key-row"><kbd>F</kbd><span>Enter or exit fullscreen</span></div><div class="key-row"><kbd>A</kbd><span>Start or stop the 25-second chapter tour</span></div><div class="key-row"><kbd>Esc</kbd><span>Close details or stop the tour</span></div><div class="dialog-note"><h3>For the booth</h3><p>Auto tour rotates through all four chapters. Selecting an item stops the tour so you can explore at your own pace. Print posters produces a landscape summary of all four chapters.</p></div><p>This exhibit explains the project. It does not connect to or control the robot, call an AI service or display live measurements. The included concept image is an illustration.</p>`));
$('#print-button').addEventListener('click',()=>{stopTour();window.print();});
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.target.matches('input,textarea,select,[contenteditable=true]'))return;if($('#detail-dialog').open)return;const k=e.key.toLowerCase();if(k==='h'||k==='0'){stopTour();navigate('home');}else if(/^[1-4]$/.test(k)){stopTour();navigate(chapters[Number(k)-1]);}else if(k==='f'){e.preventDefault();fullscreen();}else if(k==='a'){e.preventDefault();tour?stopTour():startTour();}else if(k==='escape')stopTour();else if((k==='arrowright'||k==='arrowleft')&&!e.target.closest('button,a')){e.preventDefault();stopTour();navigate(chapters[(chapters.indexOf(active)+(k==='arrowright'?1:3))%4]);}});
selectEdp(0);showChapter(location.hash.slice(1)||new URLSearchParams(location.search).get('panel')||'home',{scroll:false});
})();
