/* Editable exhibit copy. No credentials or live robot connections belong here.
   International feature plans are written as present capabilities at the team's request.
   Explicit longer-term expansion stays in future. Edit technology below for hardware updates. */
window.EXHIBIT = {
  edp: [
    {short:'Define',label:'Define the problem',title:'Protect the original. Preserve its meaning.',body:'Our challenge combines three needs: make worn inscriptions easier to see, reach them consistently and keep their information accessible.',takeaway:'Capture surviving detail without touching the inscription.',evidence:'We focused on fading inscriptions, environmental deterioration, difficult access and the specialist work needed to interpret them.'},
    {short:'Research',label:'Conduct research',title:'Understand the surface. Understand the reader.',body:'We explored inscription recording, epigraphy and the limits of a single photograph. We compared the information supplied by surface geometry, changing illumination and different light channels.',takeaway:'Combine complementary views and preserve the original capture.',evidence:'Our research connects structured light, Reflectance Transformation Imaging (RTI), multispectral capture and AI-assisted interpretation. Experts remain central to reviewing readings.'},
    {short:'Imagine',label:'Brainstorm & conceptualise',title:'Choose a system around the problem.',body:'We considered handheld capture, fixed cameras, drones, robot arms and mobile platforms. We selected a wheeled rover for positioning a non-contact scanner and carrying the required modules.',takeaway:'A mobile, modular rover brings capture and preservation into one workflow.',evidence:'Alternatives were compared against access, repeatability, affordability, portability and maintainability. Aerial access remains a longer-term research direction.'},
    {short:'Prototype',label:'Create a prototype',title:'Build in modules. Bring them together.',body:'Our development brought together the mobile base, scanning assembly, sensors, lighting, movement and processing. Laser-cut interlocking rover panels make the inner engineering accessible.',takeaway:'Separate imaging, motion, processing, power and records into clear functions.',evidence:'Early work included an Arduino obstacle-sensing rover and Raspberry Pi camera experiments. These informed the later laptop-based system and moving scanning body.'},
    {short:'Select',label:'Select & finalise',title:'Let every component earn its place.',body:'The system uses a USB camera and laptop for capture and processing, with a local controller handling motion. Cloud interpretation is backed by a local Qwen model.',takeaway:'Keep heavy processing on the laptop and bounded movement on the controller.',evidence:'Design choices evolved from earlier Pi-centred proposals. Modular construction, a motorised lift and separate sensing functions support the current architecture.'},
    {short:'Analyse',label:'Analyse our work',title:'Examine the evidence at every step.',body:'Our evaluation focuses on image clarity, lighting, camera distance, positioning, obstacle response and the consistency of complete scans. Interpretation is assessed separately from capture.',takeaway:'Compare raw and processed evidence, then inspect uncertainty and failure cases.',evidence:'The test programme covers varying light and standoff, motion repeatability, module reconnection and camera/API/network failure. We do not equate a confidence score with measured accuracy.'},
    {short:'Improve',label:'Improve Punaruttham',title:'Make each iteration more useful.',body:'We refined the rover’s status feedback, scanning movement and processing architecture. The International system brings together auto-cropping, mode selection, heatmaps, damage analysis and reports.',takeaway:'Use each observation to improve reliability, clarity and access.',evidence:'Documented revisions include servo-mounted sensing, an I²C display, red/green status LEDs and the shift to laptop processing. Our next expansion focuses on wider access and expert-led field use.'}
  ],
  featureGroups: [
    {id:'capture',title:'Capture',subtitle:'See the surviving detail',icon:'scan',intro:'A coordinated scanner records the surface without physical contact.',items:[
      ['Non-contact scanning','Record inscriptions while preserving the original surface.','The rover positions its imaging equipment at a controlled distance. Images and sensing data become a digital record without pressing recording material onto the inscription.','Protects fragile originals while retaining evidence for later study.'],
      ['Autonomous target detection','Locate the inscription and crop the relevant region.','Vision identifies an inscription-bearing area, selects a region of interest and passes its position to the scanning workflow. Auto-cropping focuses subsequent processing on the target.','Reduces repeated manual framing and keeps analysis focused.'],
      ['Automatic scan selection','Choose normal, RTI, structured-light or multispectral capture.','The system selects a capture strategy for the target and coordinates acquisition. Complementary modes reveal different aspects of the same surface.','Connects the choice of imaging method to the inscription being examined.'],
      ['Motorised lift & viewpoints','Align the scanning body with the inscription.','Height adjustment and camera positioning bring the scanning head to the target. The controller moves within its limits and signals readiness before capture.','Supports repeatable framing across inscription positions.'],
      ['Reflectance Transformation Imaging','Examine the surface under changing light.','A set of captures records different illumination directions. An interactive RTI output lets an expert relight the surface digitally; the image compilation also supports AI analysis.','Helps reveal surviving relief that is difficult to see under one light.'],
      ['Structured-light capture','Use projected patterns to examine surface geometry.','The camera records how patterns change across the surface. Calibrated geometric processing supports depth and shape analysis alongside ordinary images.','Adds geometric information to colour and texture.'],
      ['Multispectral imaging','Compare the inscription across light channels.','Separate light channels provide complementary views of the surface. They are considered alongside visible imagery rather than treated as interchangeable with thermal or depth sensing.','Expands the evidence available for analysing a difficult surface.'],
      ['Thermal, depth & dimensions','Bring additional sensing into the scan record.','Thermal imagery, geometric depth and dimension checking are separate inputs. Distance sensing helps position the scanner; surface analysis supplies shape and measurement information.','Adds context to the inscription’s appearance and geometry.']
    ]},
    {id:'analyse',title:'Analyse',subtitle:'Reveal structure & condition',icon:'layers',intro:'Raw evidence stays connected to every enhanced view and analytical layer.',items:[
      ['Image enhancement','Make subtle surviving detail easier to inspect.','Local contrast enhancement, filtering, edge information and neural processing support visual analysis. Enhanced images remain linked to their originals.','Improves inspection without replacing the source evidence.'],
      ['Before & after comparison','Compare the original capture with its processed view.','Side-by-side raw and processed images help visitors and experts see what changed during enhancement. The original remains available for independent examination.','Makes the processing transparent.'],
      ['Topography & 3D reconstruction','Explore the form of a stone or clay tablet.','Surface information is used to create relief visualisations and a 3D model. These outputs describe geometry and complement the inscription’s text record.','Makes shape available for analysis, documentation and replicas.'],
      ['Material identification','Distinguish stone and clay/tablet surfaces.','Visual and sensing information supports a material classification that informs interpretation of the scan. This label remains part of the contextual record.','Helps organise scans and select appropriate analysis.'],
      ['Damage mapping','Locate cracks, erosion and missing regions.','A visual condition layer marks damaged and incomplete areas so that surviving marks can be distinguished from missing material.','Directs attention to regions that need closer expert examination.'],
      ['Preservation-priority assessment','Highlight Stable, At Risk and Urgent records.','Condition information supports a proposed preservation-priority label. It is a decision aid for expert review, rather than a conservation diagnosis on its own.','Helps prioritise which inscriptions to examine further.'],
      ['Confidence & topographic heatmaps','Make uncertainty and surface variation visible.','Character-level confidence and surface-based visualisations indicate where an interpretation needs attention. A confidence value expresses model uncertainty; it is not an accuracy claim.','Shows where human judgement matters most.']
    ]},
    {id:'interpret',title:'Interpret',subtitle:'From traces to meaning',icon:'text',intro:'Recognition, reconstruction and translation remain distinct steps.',items:[
      ['Script identification','Identify the writing system before reading it.','The interpretation workflow considers script identity so that glyph analysis can use relevant examples and references.','Provides context for reading historical characters.'],
      ['Brahmi recognition support','Combine script references with custom AI components.','Brahmi GAN material, a Brahmi Kaggle dataset and the team’s CNN, FNN, PINN and PINO components support the interpretation pipeline.','Adds script-specific support beyond a general-purpose model.'],
      ['Transcription & transliteration','Keep what is read separate from how it is written.','Transcription records the recognised characters. Transliteration represents those characters in another writing system while retaining their link to the source.','Makes the reading easier to inspect and compare.'],
      ['Digital reconstruction','Propose readings for damaged or missing characters.','The system offers candidate reconstructions with uncertainty information. Reconstructed regions are distinguished from characters supported directly by the surviving surface.','Enables useful hypotheses without obscuring the original evidence.'],
      ['Translation','Make a reading accessible in another language.','The interpreted text is translated for understanding and sharing. The record preserves the source, transcription, transliteration and proposed meaning together.','Connects specialist readings with a wider audience.'],
      ['Cloud AI & local fallback','Continue interpretation when the API is unavailable.','Claude supports the cloud workflow. A local Qwen model provides a fallback when the cloud API cannot be used. Their behaviour and available functions depend on the local configuration.','Reduces reliance on a single online service.'],
      ['Historical reference fallback','Use a James Prinsep chart as an additional reference.','When the learned pipeline cannot resolve Brahmi characters, chart-based reference material provides another comparison route. Unresolved or ambiguous readings remain visible for review.','Keeps reference-based reasoning alongside model-based suggestions.'],
      ['Expert review & corrections','Keep the specialist in the interpretation loop.','Experts can inspect the raw evidence, compare derived views and accept, reject or correct a proposed reading. Corrections remain associated with the inscription record.','Supports accountable interpretation and better records.']
    ]},
    {id:'preserve',title:'Preserve',subtitle:'Create a lasting record',icon:'archive',intro:'The result is a connected body of evidence, interpretation and reusable outputs.',items:[
      ['Accessible digital archive','Keep inscription records available for revisiting.','The archive associates captures, important metadata, recognised text, translation and derived outputs with the same inscription.','Preserves a record beyond a single visit or demonstration.'],
      ['Interactive RTI files','Share digital relighting with experts.','The RTI compilation is saved as an interactive output for examination under different virtual light directions.','Allows detailed remote surface inspection.'],
      ['3D stone & tablet models','Preserve the shape as well as the words.','A three-dimensional model provides a reusable representation of the inscription-bearing object for study, visualisation and replica workflows.','Connects textual interpretation to physical form.'],
      ['Laser-cuttable & CNC outputs','Support museum replica production.','The output workflow includes laser-cuttable files and CNC/G-code for external fabrication. A museum can use suitable fabrication equipment to create a replica from the digital output.','Enables handling and display of replicas while protecting originals.'],
      ['Automatic scan reports','Bring the scan evidence into one document.','Reports combine images, measurements, interpretation, uncertainty and metadata, keeping the scan’s context with its conclusions.','Makes results easier to review, discuss and share.'],
      ['Originals, metadata & history','Retain the context behind each result.','Records keep original captures alongside processed views, interpretation and expert corrections. Source evidence remains available when a reading changes.','Lets future users revisit the basis of an earlier interpretation.']
    ]},
    {id:'experience',title:'Interact',subtitle:'Designed for people & places',icon:'people',intro:'A usable system makes complex evidence understandable and accessible.',items:[
      ['Persistent language profiles','Let language preferences follow the user.','A preferred-language profile applies across explanations, voice output, translations, interface and saved records.','Makes repeat use more accessible.'],
      ['Voice interaction & explanation','Offer another way to engage with the system.','Voice input and spoken explanations support hands-free interaction and museum-style interpretation alongside visual controls.','Broadens how people can explore inscription information.'],
      ['Face-authenticated accounts','Connect an identified user with their profile.','Face authentication supports recognition of a returning account and its preferences within the archive experience.','Personalises access to the user’s saved context.'],
      ['Obstacle & status feedback','Make the rover’s state understandable.','Ultrasonic sensing supports obstacle response. LEDs, a buzzer and an I²C display communicate movement, stop and workflow status.','Helps people understand what the robot is doing.'],
      ['Modular & repairable construction','Access the function that needs attention.','Scanning, motion, processing, power and archive functions are organised as modules. Removable rover panels expose components for inspection, repair and upgrades.','Supports maintainability and future module sharing.'],
      ['A complete scan-to-archive workflow','Connect physical action to a preserved result.','Detect, position, choose a mode, capture, enhance, interpret, review and archive. Each stage contributes to an understandable end-to-end preservation process.','Turns separate technologies into one coherent system.']
    ]}
  ],
  technology: [
    {id:'sensing',name:'Sense & capture',kicker:'INPUTS',icon:'scan',headline:'Several views. One inscription.',description:'Imaging and sensing provide complementary evidence about the target, its position and its surface.',components:[
      ['1080p USB camera','Primary image capture','Connects the inscription to the laptop vision and processing workflow.'],
      ['Ultrasonic sensor','Obstacle & range sensing','Acoustic distance information supports approach and obstacle response.'],
      ['VL53L1X','Optical time-of-flight ranging','A separate optical distance input supports scanner positioning.'],
      ['Thermal camera','Thermal imagery','Adds a thermal view; geometric depth is handled separately.'],
      ['Depth & dimension checking','Geometry & measurement','Supports surface shape, dimensions and topographic outputs.'],
      ['Controlled light & projection','RTI, structured light, multispectral','Changing illumination, patterns and light channels support complementary scan modes.']
    ]},
    {id:'motion',name:'Position & control',kicker:'PHYSICAL SYSTEM',icon:'move',headline:'The right view starts with positioning.',description:'The mobile base and moving scanning body align the imaging equipment. A local controller carries out bounded movement.',components:[
      ['Wheeled rover','Mobile platform','Moves the scanning assembly to a target while monitoring obstacles.'],
      ['Motorised scanning lift','Height & viewpoint control','Linear-actuator positioning moves the upper scanning body to the inscription.'],
      ['Arduino UNO R4 WiFi','Local motion controller','Receives high-level positioning instructions and coordinates actuator and status behaviour.'],
      ['Feedback & limits','Movement supervision','Position feedback, readiness acknowledgement and travel limits coordinate movement with capture.'],
      ['Servo, motors & drivers','Mechanical actuation','Directional sensing and driven movement support the scan workflow.'],
      ['LEDs, buzzer & I²C display','Visible and audible status','Communicate movement, obstacle and process states.'],
      ['Modular frame & power','Serviceable construction','Laser-cut interlocking rover panels provide access to scanning, motion, processing and power modules.']
    ]},
    {id:'processing',name:'Process & coordinate',kicker:'LAPTOP',icon:'chip',headline:'One coordinated processing workflow.',description:'The laptop is the main processing hub. Vision and geometry guide positioning; captured evidence then moves through enhancement and analysis.',components:[
      ['Laptop computing','Main processing','Runs image capture, processing, visualisation and the connection to interpretation.'],
      ['Target detection & cropping','Find the region of interest','Identifies the target area and provides location information for framing.'],
      ['Calibrated geometry','Convert target position to movement','Relates image geometry to scanner positioning; the controller confirms readiness before capture.'],
      ['Capture orchestration','Choose & coordinate modes','Organises normal, RTI, structured-light and multispectral capture.'],
      ['Enhancement pipeline','Contrast, filtering & edges','Includes CLAHE, Gaussian filtering, Sobel edge information and neural enhancement.'],
      ['Surface analysis','Shape, material & damage','Produces topography, 3D geometry, condition visualisations and measurement context.']
    ]},
    {id:'intelligence',name:'Interpret & review',kicker:'HYBRID AI',icon:'text',headline:'General intelligence, supported by script knowledge.',description:'Cloud and local models work alongside Brahmi material, custom neural components and historical references. Uncertainty accompanies interpretation.',components:[
      ['Claude API','Cloud interpretation','Supports analysis, reading, reconstruction and translation in the online workflow.'],
      ['Qwen local model','Offline fallback','Provides a local interpretation route when the cloud API is unavailable.'],
      ['Brahmi GAN & Kaggle material','Script-specific support','Reference and learning material supports Brahmi character interpretation.'],
      ['CNN · FNN · PINN · PINO','Team’s custom AI components','Neural and physics-informed components support the broader analysis pipeline.'],
      ['James Prinsep chart','Reference fallback','An additional character-reference route for unresolved Brahmi readings.'],
      ['Uncertainty & expert corrections','Human review','Separates observed text from uncertain readings and proposed reconstructions.']
    ]},
    {id:'outputs',name:'Archive & reuse',kicker:'OUTPUTS',icon:'archive',headline:'Preserve the evidence behind the reading.',description:'An inscription record connects raw data, derived visualisations and interpretation to outputs that researchers and museums can reuse.',components:[
      ['Accessible archive app','Connected records','Stores translation, metadata, raw captures and derived data together.'],
      ['Interactive RTI','Digital relighting','Allows experts to inspect surface detail under changing virtual light directions.'],
      ['3D models & topography','Shape & relief','Represent inscription-bearing stones and clay tablets digitally.'],
      ['Laser files & CNC/G-code','Replica fabrication outputs','Provide files for suitable external museum fabrication equipment.'],
      ['Scan report','Portable documentation','Collects images, measurements, interpretation, uncertainty and metadata.'],
      ['Language & account preferences','Personalised access','Keeps interface, explanations and saved-record preferences with the user.']
    ]}
  ],
  future: [
    {id:'phone',category:'WIDER ACCESS',title:'Preservation in your hand.',body:'A lower-cost phone-based companion brings guided capture and human-assisted interpretation to more people.',points:['Use a phone camera for a more accessible entry point.','Guide the user through the steps that the rover automates.','Connect captured evidence with the archive and review workflow.'],outcome:'Broaden participation beyond organisations with a full rover.'},
    {id:'modules',category:'SHARED RESOURCES',title:'A library of capabilities.',body:'Purchase, whole-robot rental and individual module rental make access more flexible.',points:['Maintain a reserve of reusable modules for short-term needs.','Record condition before and after each rental.','Repair or replace the affected component and return usable modules to circulation.'],outcome:'Make specialised equipment more affordable and maintainable.'},
    {id:'scripts',category:'DEEPER KNOWLEDGE',title:'More scripts. Stronger evidence.',body:'Expand beyond the present Brahmi focus with more expert-labelled material and better evaluated models.',points:['Build script-specific reference collections with appropriate permissions.','Evaluate transcription, reconstruction and translation separately.','Use expert corrections to improve the quality of future records.'],outcome:'Serve a wider range of inscriptions without hiding uncertainty.'},
    {id:'monitoring',category:'LONG-TERM PRESERVATION',title:'See change across time.',body:'Compare repeat scans to track erosion and changes in condition, building on today’s damage maps.',points:['Align later captures with earlier records.','Separate imaging differences from actual surface change.','Study how change over time can support preservation priorities.'],outcome:'Move from documenting a moment to understanding deterioration.'},
    {id:'pilots',category:'FIELD COLLABORATION',title:'From exhibit to field use.',body:'Work towards expert-supervised pilots with museums, universities, epigraphists and heritage organisations.',points:['Test on permitted samples under appropriate supervision.','Compare the workflow with the institution’s existing documentation.','Use feedback to improve scanning, interpretation and reporting.'],outcome:'Develop evidence of practical value in real preservation work.'},
    {id:'reach',category:'RESEARCH HORIZON',title:'Reach harder places.',body:'Explore additional platforms, including aerial access, for inscriptions beyond the rover’s practical reach.',points:['Compare reach, stability, access and capture quality.','Adapt positioning and imaging to the platform.','Retain non-contact capture and protection of the original.'],outcome:'Extend documentation to more difficult settings.'},
    {id:'provenance',category:'RESEARCH HORIZON',title:'A traceable history of each record.',body:'Explore stronger provenance across institutions, including the role of hashes, version history and optional blockchain.',points:['Keep the original capture and its derived versions connected.','Show who changed a reading and why.','Assess whether a shared ledger solves a real multi-party need.'],outcome:'Make changes traceable while keeping interpretations correctable.'}
  ],
  business: [
    ['partners','Potential collaborators','Epigraphists, universities, museums and heritage organisations.','Pilot work, reference expertise and feedback are the route to a useful preservation tool. These are intended collaborators, not claims of formal partnerships.'],
    ['activities','Key activities','Capture, analyse, interpret, preserve and support.','Maintain modules, improve models, document workflows and support institutions using the system.'],
    ['value','Value proposition','Non-contact capture with connected evidence and interpretation.','Bring repeatable imaging, visible uncertainty, accessible records and museum replica outputs into one workflow.'],
    ['relationships','User relationships','Expert feedback and ongoing technical support.','Develop the system through supervised pilots, shared review and responsive maintenance.'],
    ['customers','Intended users','Museums, universities, epigraphists and heritage teams.','The phone companion also opens an entry point for students and a wider interested public.'],
    ['resources','Key resources','The rover, modules, software, data and expertise.','Imaging hardware, reusable modules, computing, reference material and the skills to operate and maintain them.'],
    ['channels','Access channels','Direct institutional use, rental and a digital archive.','Reach users through demonstrations, expert-led pilots, institutional adoption and accessible digital records.'],
    ['costs','Cost structure','Build, maintain, transport, compute and support.','Track component replacement, repairs, setup, storage, cloud operation and rental downtime. Final prices depend on actual cost evidence.'],
    ['revenue','Access & revenue model','Purchase · robot rental · module rental.','Offer access at different scales and explore the phone companion. Commercial terms and prices will be developed from pilot needs and real costs.']
  ]
};
